# Generated by Django 5.1.6 on 2025-02-09 09:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='artists/')),
                ('contact', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('PAINTING', 'Painting'), ('SCULPTURE', 'Sculpture'), ('PHOTOGRAPHY', 'Photography'), ('DIGITAL', 'Digital Art'), ('MIXED', 'Mixed Media'), ('OTHER', 'Other')], default='PAINTING', max_length=20)),
                ('technique', models.CharField(choices=[('OIL', 'Oil'), ('ACRYLIC', 'Acrylic'), ('WATERCOLOR', 'Watercolor'), ('PENCIL', 'Pencil'), ('DIGITAL', 'Digital'), ('MIXED', 'Mixed Media'), ('OTHER', 'Other')], default='ACRYLIC', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.artist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
